hash-format = "sha256"

[[files]]
file = "config/crash_assistant/config.toml"
hash = "ca527c38540e21ba1dc8e2b213cbbc6be61919ca8fac6997e573203ae6ba663c"

[[files]]
file = "config/yosbr/config/twitchchat.json"
hash = "ef7381decde4d335458a6d539381975e30e90b189e4ce85493acac34125ec912"

[[files]]
file = "mods/advancement-plaques.pw.toml"
hash = "4e4e8652fcb8f0f011e2a28014b890e54c1adfb87770ea8e9188d04327081a8e"
metafile = true

[[files]]
file = "mods/better-sodium-video-settings-button.pw.toml"
hash = "c0940c2262d6f623afa496735695c4dd6f05252024350cb64038dc190b93bc1f"
metafile = true

[[files]]
file = "mods/chatsounds.pw.toml"
hash = "6736224481275b1f0f019b11f9d9d6184e05f14dd9b176beeb9f76b95ba75d4e"
metafile = true

[[files]]
file = "mods/crash_assistant.pw.toml"
hash = "9cdbcae661da041584f67e97ffdd537ab2eff35cc4ca2596350e7510cc7e2b20"
metafile = true

[[files]]
file = "mods/deathlog.pw.toml"
hash = "628898d7ebb5989fd8b5ae4ff8b6239d5bda705651949bcdd3de2c36c292253b"
metafile = true

[[files]]
file = "mods/item-highlighter.pw.toml"
hash = "cd27006c2c2cfe4c006c4a4da1c342f60359f076e51ab967ba578daba5dc2ce8"
metafile = true

[[files]]
file = "mods/minecart-turning.pw.toml"
hash = "f66dea816e3d1180959ca92360d169b7772716cd22175fb9735eb728f5bf7c05"
metafile = true

[[files]]
file = "mods/moremousekeybinds.pw.toml"
hash = "88bfb09fc4f01008cb0f0f23a0ff46483a135dfc13556b0e7a6ae307fd633f4d"
metafile = true

[[files]]
file = "mods/twitch-chat.pw.toml"
hash = "87e50820350630bfabcdfe2f330d311f8ee1c9e4ac19d80c633d459818f60b48"
metafile = true
