name = "Incompatible"
author = "BrailleBennett"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9447eabc95e31c7682c89ce68ae34700d24cc9d1dbbc9255ec1abf3eca903783"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9", "1.21.10"]
