hash-format = "sha256"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "5ff485f2628ce307026bc906faab14af5250dfdb86505ce4641d6e2c31e77c01"

[[files]]
file = "config/viafabricplus/jars/viabackwards.pw.toml"
hash = "0b4ae69425fc411ee206e32a8029ddf438822a49044872607629b5ec6ea7eb63"
metafile = true

[[files]]
file = "config/viafabricplus/jars/viaversion.pw.toml"
hash = "3f88d1ac0620f4296c8ba1e7d861cb16bdba342805eaecc1042cead7def45c95"
metafile = true

[[files]]
file = "config/yosbr/config/PaginatedAdvancements.json5"
hash = "3a1c71d2011cac176e00697237148ee882393b19394374862f8025f129d4c5a2"

[[files]]
file = "config/yosbr/config/bettergrass.json"
hash = "8aaf74864043e08741cc3c60f3ffe0d9aaf1fe757f111bb41064fb580d25bdf1"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "69de1a523d9ca24248233c11178b2492984ba0b25b0355242d72b2ae17a7c284"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "057e9e53790394db8b700616de3c235b0af3dc12fe7731a66ad20026acb9d991"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "70785772d8e66e1b75fa58ef0ceff1b598a78a025b05908ffd03c66cb6a1216d"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "f773c03c1cce5797e4d4698939ba8a06f421101a0403b8e018c3f3d86e752a45"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "6a3760d2b7828efc524976294cc6fd17f16bdda9d9827bd55f8fcd58ce724355"

[[files]]
file = "config/yosbr/config/fabrishot.properties"
hash = "f5ff731194f66727bfeb75a28a70104fc4687cbc84b69e60c94fe1b7d901f453"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "17225e085e6759210cec7e829e00c8c90f9c5d38714835cb5da9c98398842f7d"

[[files]]
file = "config/yosbr/config/fishontheline.json5"
hash = "b2b57bf3b277975d28772c74b659f2ee6d99211123f2f37b44cdc102a55654d0"

[[files]]
file = "config/yosbr/config/improvedsignediting.json5"
hash = "b020a794da72c73d1084afab8d5446bafdab796a96fbc02032fc7de2bab7a89e"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/isxander-main-menu-credits.json"
hash = "02f901bd1494f56a31daf63bdd1cc9af575487aff7d8e0afbb0d9903af617233"

[[files]]
file = "config/yosbr/config/jade/jade.json"
hash = "14f7013b653a8f9e7d07565fbd23be898f1e5915523c8d64885b5d77ea1b0ed6"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "57b848fb6d7c03b6124297de49b1e4cb169e74db042c74aecf79f035ae2f3980"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "ff2fb838e13e529a5939896a0775595c2e0c9d1288c7afca76ff1d3fd5646c97"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "8b36ea8af428943d85a7594b9d2e8144be3f77bab05a150e8b2db4dbe8f25a37"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "60eb0902eac918d39fb5eb7df66314f5748aef0259b4ad5bdeacd27dfff120ca"

[[files]]
file = "config/yosbr/config/phases-discord-rich-presence.json"
hash = "a6fc53ccc0de5e196af39e3ecef2eaa0d3c4bedf2e04941cb5f5012e16847060"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "4449fb9b3440c4367f861d0f8e75b879caf6c897cb47569f13929ca37d6c864d"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "3630be880dc7f037238b7e6347201d4f716ffc7e16db0a1498ef2f775cf8f5be"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "37aaf52aa7545527c7ade71ac77ad2fcf6019995bf58b6ea1fe0f52949919d18"

[[files]]
file = "config/yosbr/config/sodium-shadowy-path-blocks-options.json"
hash = "4773ede8076bdbcfb6b8ea3de058a56120aa7438ee6b25de297c10aa8f5ce393"

[[files]]
file = "config/yosbr/config/treeharvester.json5"
hash = "e5cdf0bb607976ac5af179342cdc53b9df2a88e1721db12f61448380bea8f6d7"

[[files]]
file = "config/yosbr/config/twitchchat.json"
hash = "ef7381decde4d335458a6d539381975e30e90b189e4ce85493acac34125ec912"

[[files]]
file = "config/yosbr/config/zoomify.json"
hash = "392177d784e2bdf485c1df06012af354f48404f6ef05faf9c326901055e467fd"

[[files]]
file = "config/yosbr/options.txt"
hash = "01185e1a7810a8f64fb1b915821672700e59669cb29b0804628cafb37a996300"

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "69a894ec5f411805e9d6d21d79987c90e74ccb8463c04f009c63a4b4195c6ef2"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "23b3d1ad268ba3a1eaaea01b74ff3dd5ae9123c0cb0ba29ec85c98b0e6eadfba"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "659f7b849f370718cc5216c3de0fdc4863391f9889d00ebd4ccef8274ee7026d"
metafile = true

[[files]]
file = "mods/audio-navigation.pw.toml"
hash = "229c39c8ba204d5d1ae73a53228661c71f8b97d43471a2dd5e126c01df40d0f4"
metafile = true

[[files]]
file = "mods/better-beacon-placement.pw.toml"
hash = "a8773b4dae6219a6200315d3870540d0c6e43e830387587ef8eaa1d31a109595"
metafile = true

[[files]]
file = "mods/better-conduit-placement.pw.toml"
hash = "d7379cfede5d9cc086643350ef534c7708da5fb9e253dea555254a630598beab"
metafile = true

[[files]]
file = "mods/better-sign-edit.pw.toml"
hash = "b9a82100140e944b4e9bbbfc975a0cbe64b42a60ac6efd46203cd9d3eaf01bf9"
metafile = true

[[files]]
file = "mods/bettercommandblockui.pw.toml"
hash = "6446c5ee6bbb7de5546b0296d86195b16e1479c0cb710bbb135d871c2cf24ca1"
metafile = true

[[files]]
file = "mods/bettergrass.pw.toml"
hash = "8c4051285a26835f261d0f7ebc5170d27e072c22185cb445c27502502f730567"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "24b0177dacb547321d83487699e13bf6f6fa004c0d8199dbcc0867b2c21097ee"
metafile = true

[[files]]
file = "mods/biome-spawn-point.pw.toml"
hash = "7925e688d5055a5a45a286ddf6298f9ebbb028f8144f6828c2293c9f4ee9d22f"
metafile = true

[[files]]
file = "mods/blossomhomes.pw.toml"
hash = "0ae67f07d6b6cb9bf11055ff17c3d33772138e57a1ddd42bdfa38f098b524127"
metafile = true

[[files]]
file = "mods/blossomlib.pw.toml"
hash = "df6683dfde27cd17dc4db958a5e87711a75184a1236b6c3dac6c85a2bf5b89fa"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "d7384472a7c1c58b70d0b27e3681f79082e87150402c8bab4eda8e77a8209a7a"
metafile = true

[[files]]
file = "mods/clientsort.pw.toml"
hash = "d815fedf89b893951e599e0765746e3e9b6c1091555120a38e6c71df2982601d"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "91ec280bb0b40533a4f43601f074eb0d3ff52a606cd0a3b700802b228670f4ef"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "3d24d58b2caf4fd73d76b2d734a1d06490994d5d38177376e6f5d8d9f8fb87e0"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "59060a934906e4cbd6a19b91ab63e40761de5699166366bf2e0e6d2062aec539"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "dcd43d7df3b82c967383cbbe3990e4b08ebafce5c1704c698c43c5dcbed4bc28"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "da925d1159906a6c993fa4be167a48ae350d77daa1950a68135bf56c4e0dbb62"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "d61eea65d903963fc412f1e6dc4ec5c9f89814358e324cb734e0ec6e40ece483"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "867f8e4be9bc139a517dbcf55aefc2938c5e461640bd08024ec4716fce068025"
metafile = true

[[files]]
file = "mods/despawning-eggs-hatch.pw.toml"
hash = "65c7beb117599d5f5b70c590e1cb32256286eb3cdeec919bf2042aac362b5a75"
metafile = true

[[files]]
file = "mods/double-doors.pw.toml"
hash = "e2f973e44f7e2d1792bce06a056b4353fcba8fe3b28c58cda5e22308578a1534"
metafile = true

[[files]]
file = "mods/dynamic_fps.pw.toml"
hash = "eefd50e6d423f5a695752d32a69a061ed91245de0b874b243a08d50292aea0e5"
metafile = true

[[files]]
file = "mods/easy-elytra-takeoff.pw.toml"
hash = "236b160d1128e93b1125c90597205b049d16100e8f1be5a6239bdd1fa0bccfca"
metafile = true

[[files]]
file = "mods/end-poem-narration.pw.toml"
hash = "7f36fb55ae73cefaf2a780b5f2594962b3be8f6ebf2aa3e588b59e97bdc0d62d"
metafile = true

[[files]]
file = "mods/entity_model_features.pw.toml"
hash = "8d03826b68e203190ca92514d6c1c778b1ecc846fe8c669028934deadc460fde"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "f4d3b401cb1ba95d52d140f09504721f3d59aceead160b81006952dcb3e8ebfd"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "da144e39fe73c95bd65273b9cab1b89d0c8e30842f65fd35ad01adacfe1b6f5c"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "cbda4f1881cfb9f054395a3db225df4202d1f2e7bd0ed27d803b837fcf728621"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "1bbacf4844881b1367ff761b3ce1c5cc7ef61eb6514d3a7f41cc994e43cc57da"
metafile = true

[[files]]
file = "mods/fish-on-the-line.pw.toml"
hash = "c23b587af42a3b93b3da059e1ad8730678a1b636d89d62a141debed2a3014d43"
metafile = true

[[files]]
file = "mods/followers-teleport-too.pw.toml"
hash = "e5b6142cf971ea8eb5977374d47e30f5f563d5d675ebce3c79af4839793225d3"
metafile = true

[[files]]
file = "mods/forgeconfigapiport.pw.toml"
hash = "c9c2a5b3c98d4b80ac6b24db9a31435f1ec5d95aa4a442c757d83fca0b844088"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "dc14a906254d528b5ce82c0617c7e15d1ebbd17e4dcc2e852719fad60e8aa2b5"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "6b70ba49abcc5c370ab7274cca73c21f8d09afc00ee3aa8a0aa9b17e3aa1cbd2"
metafile = true

[[files]]
file = "mods/improved-sign-editing.pw.toml"
hash = "ca3f67574e97e9a722d19f497ad4b69080433a394a01183c5c60efdf0d3e71c1"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "62561bf68477f12ddcec55faf3864b9960a85ca07f9c86e6715010d8f07f398b"
metafile = true

[[files]]
file = "mods/isxander-main-menu-credits.pw.toml"
hash = "21843e75802603fc737c7599bbd6550e85d77e882e9b0aa5df279ae1270392d6"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "a077e0482f50add9ef20e962a7939aa678583cb3f354fb6b6124219badafdd4d"
metafile = true

[[files]]
file = "mods/keep-my-soil-tilled.pw.toml"
hash = "56a1343b92ed601c23cf9d8bce83341c4ed3c1893588487c7f5e8a82f4a1a59c"
metafile = true

[[files]]
file = "mods/lambdynlights.pw.toml"
hash = "4921edf5972f5acc2f39cac62324a90d33577038f074ef2afa756d17d5a84ced"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "03e1948cee78c0b9817f98ee55b8e155220498f66ec96b21f8a458098105aa4e"
metafile = true

[[files]]
file = "mods/minecraft-access-1.11.1-SNAPSHOT+fabric.jar"
hash = "04b402e7365c32a48db24a1932af583b22808f3d585870cf36b197ee208abe7e"

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "20853b64aec9d938a92a6b3b45158b67159f16bd2c08b659aea6e29df23d3be1"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "5dd45d5fd5e1ae2bd521b93a70b83c69b57ada18f424c6562d8c6ea9980cfb3e"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "c3d0746be98e5f5eaf1731a84e84724289f45f6b49836c5106e8d4669d3f84ec"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "6006fa2a1c9e1ecb4faf424b2a4c0086ad18077f6cc22c0d25fe59f1d3839900"
metafile = true

[[files]]
file = "mods/optiboxes.pw.toml"
hash = "132b5a76676415aaffb9b300cd682883a3be71c46b21da690ed1e40a9c7d2e58"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "12a352db8929bf7097972a12ef85619f695a611d268829efd263ddd80186f33e"
metafile = true

[[files]]
file = "mods/ore-harvester.pw.toml"
hash = "1ac15ebcf98e2ddefab39ab55b88f28faae4131336b62675571a0224b9d10340"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "cbe531f3cb8cd726ba811e3f8c4803ee7c3485be0ed6fce91908aa80a55c907e"
metafile = true

[[files]]
file = "mods/phases-discord-rich-presence.pw.toml"
hash = "466929fd31b2f28330f15021dd0a4a95b254fcac3b16d480ff11a23d2ff93efb"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "1d0b4cb5d19919e7c63ece2bda6e312ca80f266880e6472182cda993d70ed8fb"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "21e4d4762f06338aee170e8a402c5dd2d6ead3a43c1add2bd800ff0b61668a4b"
metafile = true

[[files]]
file = "mods/recipe-commands.pw.toml"
hash = "06894e2e00124b3aa801188913c2f3f9ef03c9cec8f9fed014c29f373956f359"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "f67ece3f1b7752cd197d5b4dd75b8d7c96b6efd91482049955a6903c3660638d"
metafile = true

[[files]]
file = "mods/replanting-crops.pw.toml"
hash = "986f4b480a15caf5a3fa6fcbad4304934e7a9f6f9197159cd7f4a59ea18e17b1"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "b039f55985a83e7ed5f5004a21ee3d0faa5f566ee5c8b595718febfc3e4a75e5"
metafile = true

[[files]]
file = "mods/scaffolding-drops-nearby.pw.toml"
hash = "d1c95567a4b931760c4731e2778a77fe167e6d283cf3087916c58f03fabef8cb"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "5ae220cfbb26641c68740ad0166c78f353680886fc28087e63bf07280a47ddbb"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "efcffa8f7f5d49fd57b52fc29ec85eecca4df3807335b8f17d0620cb6ba26a42"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "1b05c3d841542fdce7815a7fcef89e73f01a754943f292cb1e81e047cb3db362"
metafile = true

[[files]]
file = "mods/sound-controller.pw.toml"
hash = "de3675723312880194c9333c0a1c56787639be59d8638d4b1d37d68d87a64fc6"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "b1001cd1d887748ba489f32e4520e5b75a685a12a52579a906b56573ef62fe72"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "2520b331c2b0eb582b448c4ebf1a73d66d42184acc2d74912baef4140e05ee9b"
metafile = true

[[files]]
file = "mods/sspb.pw.toml"
hash = "9a7b77d36b9aba3015e540205750b0bc64223afee043a7146708e26d1e501af9"
metafile = true

[[files]]
file = "mods/stack-refill.pw.toml"
hash = "cd1d4c8b2ad6df29e9f152301f51f46b5c4641882dc20d5eef8934e58fd70e77"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "c4f0a7342d8cd2c9c7bf68b84f6169eeec909915cc278161f54003e03f2cab01"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
hash = "f51886499973a9a5c55c78d08c395e1c83af76ea7a560a0c88c91d973fe14246"
metafile = true

[[files]]
file = "mods/viafabricplus.pw.toml"
hash = "97da8aa107b5934bc6a37756a8ff3458565666c4433dce7f7021db6d238e8100"
metafile = true

[[files]]
file = "mods/yet_another_config_lib_v3.pw.toml"
hash = "32402404edd94b0dc82feb237bf4159b3460c12fe0371a9b52cbabb30da92b48"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3bf16ef57d8e5a916e8971ab9cc7cd90644d82932233b7e1e2293d95680fac4b"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "22052f42b1b73226d9508ef42af962471c79c7daa281aac66a82a90c7d7bb9e5"
metafile = true

[[files]]
file = "resourcepacks/Translations_for_Sodium.pw.toml"
hash = "198fcfb73cc9f2d32a75ca457d63ea8d995c66095df781aea0d3a79ba8e2bd02"
metafile = true

[[files]]
file = "resourcepacks/high-contrast-extended.pw.toml"
hash = "a973f853563cf93fc53c9d9162e9502565bb1fb5bfb8a6b9dad028cd4bf0f5d8"
metafile = true

[[files]]
file = "servers.dat"
hash = "43b1f9f289bbe78d537aecf4383834e2a4f09b76a6fe8266365323103375e1b6"
