hash-format = "sha256"

[[files]]
file = "config/debugify.json"
hash = "041e0e3b91b6a51364414ba03737e5b5c55b23abd089705109d5b154022e3250"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "bfe35cbe59f6c1e43cc5c7a76549f1c90bb5047d9d7152d002269a2c6a0d10d6"

[[files]]
file = "config/modpack_defaults/config/PaginatedAdvancements.json5"
hash = "3a1c71d2011cac176e00697237148ee882393b19394374862f8025f129d4c5a2"

[[files]]
file = "config/modpack_defaults/config/bettergrass.json"
hash = "8aaf74864043e08741cc3c60f3ffe0d9aaf1fe757f111bb41064fb580d25bdf1"

[[files]]
file = "config/modpack_defaults/config/capes.json5"
hash = "69de1a523d9ca24248233c11178b2492984ba0b25b0355242d72b2ae17a7c284"

[[files]]
file = "config/modpack_defaults/config/citresewn.json"
hash = "057e9e53790394db8b700616de3c235b0af3dc12fe7731a66ad20026acb9d991"

[[files]]
file = "config/modpack_defaults/config/debugify.json"
hash = "041e0e3b91b6a51364414ba03737e5b5c55b23abd089705109d5b154022e3250"

[[files]]
file = "config/modpack_defaults/config/dynamic_fps.json"
hash = "f773c03c1cce5797e4d4698939ba8a06f421101a0403b8e018c3f3d86e752a45"

[[files]]
file = "config/modpack_defaults/config/entity_texture_features.json"
hash = "6a3760d2b7828efc524976294cc6fd17f16bdda9d9827bd55f8fcd58ce724355"

[[files]]
file = "config/modpack_defaults/config/fabric_loader_dependencies.json"
hash = "6d4796ad30c71ba948580b669f4b9371f7c60a14cc54a1c3f82bae14ce90bab6"

[[files]]
file = "config/modpack_defaults/config/fabrishot.properties"
hash = "f5ff731194f66727bfeb75a28a70104fc4687cbc84b69e60c94fe1b7d901f453"

[[files]]
file = "config/modpack_defaults/config/fastquit.toml"
hash = "17225e085e6759210cec7e829e00c8c90f9c5d38714835cb5da9c98398842f7d"

[[files]]
file = "config/modpack_defaults/config/fishontheline.json5"
hash = "b2b57bf3b277975d28772c74b659f2ee6d99211123f2f37b44cdc102a55654d0"

[[files]]
file = "config/modpack_defaults/config/improvedsignediting.json5"
hash = "b020a794da72c73d1084afab8d5446bafdab796a96fbc02032fc7de2bab7a89e"

[[files]]
file = "config/modpack_defaults/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/modpack_defaults/config/isxander-main-menu-credits.json"
hash = "02f901bd1494f56a31daf63bdd1cc9af575487aff7d8e0afbb0d9903af617233"

[[files]]
file = "config/modpack_defaults/config/jade/jade.json"
hash = "14f7013b653a8f9e7d07565fbd23be898f1e5915523c8d64885b5d77ea1b0ed6"

[[files]]
file = "config/modpack_defaults/config/midnightlib.json"
hash = "57b848fb6d7c03b6124297de49b1e4cb169e74db042c74aecf79f035ae2f3980"

[[files]]
file = "config/modpack_defaults/config/modernfix-mixins.properties"
hash = "ff2fb838e13e529a5939896a0775595c2e0c9d1288c7afca76ff1d3fd5646c97"

[[files]]
file = "config/modpack_defaults/config/modmenu.json"
hash = "b7b9cdc1e99bdfd86052e373dc3e0ae87c73760816454b801b09d0cfd7b79604"

[[files]]
file = "config/modpack_defaults/config/moreculling.toml"
hash = "60eb0902eac918d39fb5eb7df66314f5748aef0259b4ad5bdeacd27dfff120ca"

[[files]]
file = "config/modpack_defaults/config/phases-discord-rich-presence.json"
hash = "a6fc53ccc0de5e196af39e3ecef2eaa0d3c4bedf2e04941cb5f5012e16847060"

[[files]]
file = "config/modpack_defaults/config/puzzle.json"
hash = "4449fb9b3440c4367f861d0f8e75b879caf6c897cb47569f13929ca37d6c864d"

[[files]]
file = "config/modpack_defaults/config/rrls.toml"
hash = "3630be880dc7f037238b7e6347201d4f716ffc7e16db0a1498ef2f775cf8f5be"

[[files]]
file = "config/modpack_defaults/config/sodium-options.json"
hash = "37aaf52aa7545527c7ade71ac77ad2fcf6019995bf58b6ea1fe0f52949919d18"

[[files]]
file = "config/modpack_defaults/config/sodium-shadowy-path-blocks-options.json"
hash = "4773ede8076bdbcfb6b8ea3de058a56120aa7438ee6b25de297c10aa8f5ce393"

[[files]]
file = "config/modpack_defaults/config/treeharvester.json5"
hash = "e5cdf0bb607976ac5af179342cdc53b9df2a88e1721db12f61448380bea8f6d7"

[[files]]
file = "config/modpack_defaults/config/twitchchat.json"
hash = "ef7381decde4d335458a6d539381975e30e90b189e4ce85493acac34125ec912"

[[files]]
file = "config/modpack_defaults/config/zoomify.json"
hash = "392177d784e2bdf485c1df06012af354f48404f6ef05faf9c326901055e467fd"

[[files]]
file = "config/modpack_defaults/options.txt"
hash = "7396eecfd0b64533e7017f75dcf250b912694ce038f0833c518cd6798d7c3bf2"

[[files]]
file = "config/viafabricplus/jars/viabackwards.pw.toml"
hash = "16b0738c95c4c6ab6eaad735a21482039a4fe307b791a324ec918c7f4143cc7e"
metafile = true

[[files]]
file = "config/viafabricplus/jars/viaversion.pw.toml"
hash = "894d3efb3b1e5f8c96c619f32f282f57dd467a29f9eb387ca2639e353f72d000"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "564ba07765d3894f54a5d8886db7cf4b8c8fb8c83f18c8cfb1f042a115b44724"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "23b3d1ad268ba3a1eaaea01b74ff3dd5ae9123c0cb0ba29ec85c98b0e6eadfba"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ff1763afa21669a76a9ca65735944986ec4ef7a0d440b98ee2154aafa46356c8"
metafile = true

[[files]]
file = "mods/audio-navigation.pw.toml"
hash = "229c39c8ba204d5d1ae73a53228661c71f8b97d43471a2dd5e126c01df40d0f4"
metafile = true

[[files]]
file = "mods/better-beacon-placement.pw.toml"
hash = "a398945ada40375f96c82913f431039f95b25bbfb06843fdc44a471997e769c7"
metafile = true

[[files]]
file = "mods/better-conduit-placement.pw.toml"
hash = "d176282ce3494687f2880171c33b3afa8c7827505d6b6f8785b90aaa5e9b7845"
metafile = true

[[files]]
file = "mods/better-sign-edit.pw.toml"
hash = "b9a82100140e944b4e9bbbfc975a0cbe64b42a60ac6efd46203cd9d3eaf01bf9"
metafile = true

[[files]]
file = "mods/bettercommandblockui.pw.toml"
hash = "cb452d78801aba186caee80fe25de1ad39b4b9b31ca42bccd6f12bf54fbfef2c"
metafile = true

[[files]]
file = "mods/bettergrass.pw.toml"
hash = "71e3d4feab82b55e84966cfe8e162aa021eeda662276d019ca4daff2abb692d2"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "24b0177dacb547321d83487699e13bf6f6fa004c0d8199dbcc0867b2c21097ee"
metafile = true

[[files]]
file = "mods/biome-spawn-point.pw.toml"
hash = "5c303b85dea2d75055c4063eb75d64801530b0d16c49b5c479792cfbd8c70f29"
metafile = true

[[files]]
file = "mods/blossomhomes.pw.toml"
hash = "a236e7aed1f8ef932ef0f50e210ebb349c82e53c52482ef8ff48797586f1b26b"
metafile = true

[[files]]
file = "mods/blossomlib.pw.toml"
hash = "e5ab7f2a2fb4520d498ee76e5c0d743020cad0422199db532828482d393fcf3e"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "35b9793a1e87175951af122d2cc46ca116679667dce4f51288e1ea7c42dc987a"
metafile = true

[[files]]
file = "mods/clientsort.pw.toml"
hash = "6aabfdc03573ae206910ad77b57c821f453fb2508c93972d0a9bb47dda54f3ca"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "4548677ce03174ad536896e445cb4b77f7757bdfa957592084ea31b02941b2c7"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "c2a61b492dd0d7a156e15b7572adb40552b94c09658cc3c6d7faf99288d094c7"
metafile = true

[[files]]
file = "mods/config_manager.pw.toml"
hash = "78b213f4555c13cbdb5346ea8c879b7210b1a04d785d05adf314f66ad1ec056a"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "caef3fa85dbb541d56e979062fff9d624e3e0a2f7f31949424fca569bf4fb958"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "4cd438bb56ad3a88f1495e12b52c005b035ee6983ddca1edf924af5298a2a787"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "d8e2eb843f684b6abe48010c4ebf3e1300bd0fe9a4132e2744757d850171f4b7"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "e661900027e02f1d44f54559e8d67a0b3b507b831be4eb05ab73a0133b22791e"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "b2cd070e7fab1d292c980e52e78279e06a62ad8fb8628a5e2a5f0ff5d9882455"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "1032eb85c10b44f283742f362ce4f37f8eea55f724aa503f8f229fb4936099ed"
metafile = true

[[files]]
file = "mods/despawning-eggs-hatch.pw.toml"
hash = "bb8a6eaf45a80de1e6326c2167d53c1011739d0239d712fd374ee6bdb67aa9f4"
metafile = true

[[files]]
file = "mods/double-doors.pw.toml"
hash = "ce3499145d0b811718c9df87ce121eacf9f45abf8589147676a6d9f7c33a6a3d"
metafile = true

[[files]]
file = "mods/dynamic_fps.pw.toml"
hash = "90456935074de94fa2b373c4f4b1257d8b036b4610a38d8364f08fe9feef948d"
metafile = true

[[files]]
file = "mods/e4mc_minecraft.pw.toml"
hash = "1ab2a6ac0ad703dc27e4fd7e6355320f8cb24367b42b7872ac658e1992b8a508"
metafile = true

[[files]]
file = "mods/easy-elytra-takeoff.pw.toml"
hash = "8085c6585ed1c543363eb1c3c3fa563190b19847bd38fab75e67dc5254fa686e"
metafile = true

[[files]]
file = "mods/end-poem-narration.pw.toml"
hash = "08a8941fc4f3fe37ebd129c813c636ddb8f13e8cb819393763ac39cdeeccd4c8"
metafile = true

[[files]]
file = "mods/entity_model_features.pw.toml"
hash = "c9e16da01642c0a107b6ee9c9447e57dc9382cddb92d39c677218341d39a1139"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "30a92fcf4367a7623cc6fae3c711861fe73826dc822c2a3aba4c694c524e11fc"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "a985ddd1d4e924a9bb286118e1418bcd193c896c78ea0114d6a87c0102a21e89"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "39b4f43a271700276ff1ae632cf05f90b85f79670d955b50ced036e363a0efe9"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "e304a0ee12891d2915581e41dbf5695c2aba7cf7fe62295525c19cc0ea72b130"
metafile = true

[[files]]
file = "mods/fish-on-the-line.pw.toml"
hash = "799be57b8c8c6e4153e5c748636fe083701edfd64c174d88329f5574dd462133"
metafile = true

[[files]]
file = "mods/followers-teleport-too.pw.toml"
hash = "3a823b201b193c65b137bd1f78d54c3f9202684de80fc4afd707af3194f45432"
metafile = true

[[files]]
file = "mods/forgeconfigapiport.pw.toml"
hash = "f21073ecab797a66025836a6fd6deeb43e2a42d5e711aa8aaf6ce84cc4ece7c0"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "b748f3c5782acd14bc088ab235b949bd3237a246c7221e06b7bc25d9310daa73"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "264a3c057c84aec673b80820d79fafe301a9dd1f0f43e2cfb901f97e1d4bd47b"
metafile = true

[[files]]
file = "mods/improved-sign-editing.pw.toml"
hash = "b09f3c807a6addbef8652585613eabc621d2744285db2e3dc4b3bbb2ae2e6eeb"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "e3541c2c9f9c40b892416fc8aad1c63fe944843c499aaee998ae5de0a4e5197c"
metafile = true

[[files]]
file = "mods/isxander-main-menu-credits.pw.toml"
hash = "21843e75802603fc737c7599bbd6550e85d77e882e9b0aa5df279ae1270392d6"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "21caf1cc09d510a23284e704cb5211408085d5964e5d6ca129fc0dc175c8fb79"
metafile = true

[[files]]
file = "mods/keep-my-soil-tilled.pw.toml"
hash = "c112895ef336f26bdce629d6c5011bc78e4aa4ed6f3340a1f88b29b182cded9b"
metafile = true

[[files]]
file = "mods/lambdynlights.pw.toml"
hash = "c4daa01ee591308f371c3c179b47ca19205f5472bf328ace5e5da61887a29d0f"
metafile = true

[[files]]
file = "mods/languagereload.pw.toml"
hash = "25cdd12e5566c068ad90462ee57f518a73bbacefaa3457f043a13efdd0f53513"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "d092368596299fdea95ebc92ca2ff45e2032444e6f9c6504669402f935d63e17"
metafile = true

[[files]]
file = "mods/minecraft-access-1.12.0-alpha.2.SNAPSHOT+fabric.jar"
hash = "bd123e290e4d013f61c65e7b5c61050bc9418989620474395769702ccb54e5ff"

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "51ff93e279e03cb3cd77a5be0df777cdcd975d35b5149180d9dc724e47168c76"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "c3d0746be98e5f5eaf1731a84e84724289f45f6b49836c5106e8d4669d3f84ec"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "42bea76780aec9949e1d84afe2eb1291c34d0788154e43a29b3727b486d119c8"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "f5273d4065ede04639ac6796cac0420d6cafed743a930a8f2c70f6f9c37e7bf3"
metafile = true

[[files]]
file = "mods/ore-harvester.pw.toml"
hash = "fdbeca76dd6617f785481b6ceefbedde94527531dc0b51d22aeb09bde4eb375e"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "b90549e496b068853f67c5486c5befb54cd0e11cb3cc1162cfadfec1b1fed354"
metafile = true

[[files]]
file = "mods/phases-discord-rich-presence.pw.toml"
hash = "30c6daf53e13db95969f0f43311e7a2fadb8871817f00bfa8eedd056d36dcf26"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "8da1c0d2c964fb36ac1ddfd51d6dd68c972bb9e039f723f7ebb7d9d42ae9cc4e"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "13369d7a10a47895f33629f000945d6bdf43f7b19a9ff1ca2ecfbc209c1ac431"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "6bb3b06ba89f2656ed8eee7a4534bacb8a461aa80ffee38546b216778592e9eb"
metafile = true

[[files]]
file = "mods/recipe-commands.pw.toml"
hash = "fe5cf2041f11f5a14a050aa1ab4d4537ed97781fa19acea40675557b9f5d0b42"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "c808a22177953198f6b9df2ae9aefca3ccd7fa0684b76ed7fdbd13e9c0f99d79"
metafile = true

[[files]]
file = "mods/replanting-crops.pw.toml"
hash = "053899f5351a2d357fd731c214021420cb6e353a548ea9be5db587df4f66db4d"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "cf86421945979fa0c512a8c5ef212177db28a3de17d4d0b36021c91da3543991"
metafile = true

[[files]]
file = "mods/scaffolding-drops-nearby.pw.toml"
hash = "fb0443bdca73eca311195a21fe9d0a6f5734f180f6b78397ebfc007da070c0f9"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "77f6ba8f063840c0d8a58bba2cedc2743d136c1d51cdd28d3506d19e167e08d5"
metafile = true

[[files]]
file = "mods/skyboxify.pw.toml"
hash = "af80a45db8c80c70745b608fca04e2890a2ca2eac3a4cf49891451b9d66b078e"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "64b2f58961347e9590e1b57078fc1270b1c489703e0744979b4d3c338b437b7a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "e8de8160961096a82125e1a81abb34bf3d4b32b8eadd41939b4d45eb2360dc20"
metafile = true

[[files]]
file = "mods/sound-controller.pw.toml"
hash = "6336d9920227dc21d6df421414bfef75a8e029ff5d8e6d36dbd3609ce1beee79"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "19f9479c1a4b9e5dee34eab19bcb54944a2044f69e58408fb85e7d1d5ce333dd"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "c073f13897a838e3c409e46b8a1d8cb510d6a6584dd815aeadaf4886f1779513"
metafile = true

[[files]]
file = "mods/sspb.pw.toml"
hash = "02b501d90c32539cf2bb25204bbc8d68c227ebed4fbeafc1e8b3c75c5aa075b4"
metafile = true

[[files]]
file = "mods/stack-refill.pw.toml"
hash = "2b353bc499f08c16f8745bc07b8da39e68ba47d77416b4fe3a3abf6745e35aec"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "c4f0a7342d8cd2c9c7bf68b84f6169eeec909915cc278161f54003e03f2cab01"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
hash = "6ba9df7457db51b556d22c0d50201071dbbbf234c6e606f2674ee9155850a8c5"
metafile = true

[[files]]
file = "mods/twitch-chat.pw.toml"
hash = "afc1c2640bb1eb7cc9a4937446ee729f98bc930eb0a085fd10cf04e9a5d5d1ff"
metafile = true

[[files]]
file = "mods/viafabricplus.pw.toml"
hash = "93c28ebe9df5e347d5a4d7f862d079cd8582bb25d8470b57c1464a56ecdd637e"
metafile = true

[[files]]
file = "mods/yet_another_config_lib_v3.pw.toml"
hash = "fed427d0c3a97020b0f695f8538a37c5a82b8bf6f16a4df7e76dd7a8bc1f0dd8"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "671e1badbd1d6b1fe20851202a5328f0600534af609afb0b8b1a0840aa222246"
metafile = true

[[files]]
file = "resourcepacks/Translations_for_Sodium.pw.toml"
hash = "53c42f11154e40b6484d6f36fc38972b0f9931fa38a555dc637204bb1f648c7e"
metafile = true

[[files]]
file = "resourcepacks/high-contrast-extended.pw.toml"
hash = "19f793a32fb8c3b98a517aeb2821dc9b7cedbffd9eae84e4d9e4bfeceee8ca51"
metafile = true

[[files]]
file = "servers.dat"
hash = "43b1f9f289bbe78d537aecf4383834e2a4f09b76a6fe8266365323103375e1b6"
