name = "Visually Impaired Access Mods+Fabric"
author = "BrailleBennett"
version = "2.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41de9ede7b84a5f3485fe42d79e0db9e318dc160247435ab55638637acdab0d6"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9", "1.21.10"]
